export enum E_ERROR {
  LOGIN_FAIL = 'LOGIN_FAIL',
  REGISTER_FAIL = 'REGISTER_FAIL'
}

export enum DIALOG_TYPE {
  REGISTER = 'REGISTER',
  EDIT = 'EDIT'
}

export enum ERROR_TYPE {
  UNIQUE = 'UNIQUE',
  REQUIRED = 'REQUIRED',
}

export enum DATA_MODEL_TYPE {
  KEY = 'KEY',
  FOREIGN_KEY_BRAND = 'FOREIGN_KEY_BRAND',
  FOREIGN_KEY_LOCATION = 'FOREIGN_KEY_LOCATION',
  FOREIGN_KEY_COMPANY = 'FOREIGN_KEY_COMPANY',
  FOREIGN_KEY_USER = 'FOREIGN_KEY_USER',
  FOREIGN_KEY_PRODUCT = 'FOREIGN_KEY_PRODUCT',
  DATA = 'DATA',
}

export enum DATA_MAPPING_VALUE_TYPE {
  UUIDV = 'UUIDV',
  RANDOM_CODE = 'RANDOM_CODE',
  EMPTY_STRING = 'EMPTY_STRING'
}

export enum SHIPMENT_INFORMATION_TYPE {
  SET_PRODUCT_SUCCESS = 'SET_PRODUCT_SUCCESS',
  SET_PRODUCT_FAIL = 'SET_PRODUCT_FAIL',
  ADD_SERIAL_NUMBER = 'ADD_SERIAL_NUMBER',
  DUPLICATE_DATA = 'DUPLICATE_DATA',
  CHECK_FIRST_ERROR = 'CHECK_FIRST_ERROR',
  SOMETHING_ERROR = 'SOMETHING_ERROR'
}

export enum LIST_DATA_TYPE {
  ALL = 'All',
}


